/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import DrawUI from "./JJExport/View/DrawUI"
import AutoFixPosY from "./JJExport/Libs/AutoFixPosY"
import FinishGameUI from "./JJExport/View/FinishGameUI"
import FriendGameUI from "./JJExport/View/FriendGameUI"
import FullGameUI from "./JJExport/View/FullGameUI"
import FixNodeY from "./Libs/FixNodeY"
import NewGameUI from "./JJExport/View/NewGameUI"
import ProgramUI from "./JJExport/View/ProgramUI"
import RecommendUI from "./JJExport/View/RecommendUI"
import ScrollUI from "./JJExport/View/ScrollUI"
import BoxUI from "./View/BoxUI"
import FixAdShareIcon from "./Libs/FixAdShareIcon"
import FinishUI from "./View/FinishUI"
import FreeSkinUI from "./View/FreeSkinUI"
import GameUI from "./View/GameUI"
import GameTopNode from "./View/GameTopNode"
import KillBossUI from "./View/KillBossUI"
import LoadingUI from "./View/LoadingUI"
import OfflineUI from "./View/OfflineUI"
import SkinUI from "./View/SkinUI"
import FixAiTips from "./Crl/FixAiTips"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="MyScenes/LoadingUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("JJExport/View/DrawUI.ts",DrawUI);
        reg("JJExport/Libs/AutoFixPosY.ts",AutoFixPosY);
        reg("JJExport/View/FinishGameUI.ts",FinishGameUI);
        reg("JJExport/View/FriendGameUI.ts",FriendGameUI);
        reg("JJExport/View/FullGameUI.ts",FullGameUI);
        reg("Libs/FixNodeY.ts",FixNodeY);
        reg("JJExport/View/NewGameUI.ts",NewGameUI);
        reg("JJExport/View/ProgramUI.ts",ProgramUI);
        reg("JJExport/View/RecommendUI.ts",RecommendUI);
        reg("JJExport/View/ScrollUI.ts",ScrollUI);
        reg("View/BoxUI.ts",BoxUI);
        reg("Libs/FixAdShareIcon.ts",FixAdShareIcon);
        reg("View/FinishUI.ts",FinishUI);
        reg("View/FreeSkinUI.ts",FreeSkinUI);
        reg("View/GameUI.ts",GameUI);
        reg("View/GameTopNode.ts",GameTopNode);
        reg("View/KillBossUI.ts",KillBossUI);
        reg("View/LoadingUI.ts",LoadingUI);
        reg("View/OfflineUI.ts",OfflineUI);
        reg("View/SkinUI.ts",SkinUI);
        reg("Crl/FixAiTips.ts",FixAiTips);
    }
}
GameConfig.init();